project_name: chart-releaser
snapshot:
  name_template: '{{ .Tag }}-next'
checksum:
  name_template: '{{ .ProjectName }}-checksums-{{ .Tag }}.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
release:
  github:
    owner: vapor-ware
    name: chart-releaser
  draft: false
  prerelease: auto
  name_template: '{{ .Version }}'
before:
  hooks:
    - go mod tidy
builds:
  -
    main: ./cmd/chart_releaser.go
    binary: chart-releaser
    env:
      - CGO_ENABLED=0
    ldflags:
      - -w
      - -X pkg.BuildDate={{ .Date }}
      - -X pkg.Commit={{ .ShortCommit }}
      - -X pkg.Tag={{ .Tag }}
      - -X pkg.Version={{ .Version }}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
dockers:
  - use: docker
    goos: linux
    goarch: amd64
    image_templates:
      - 'vaporio/chart-releaser:{{ .Tag }}'
      - 'vaporio/chart-releaser:{{ .Major }}'
      - 'vaporio/chart-releaser:{{ .Major }}.{{ .Minor }}'
      - 'vaporio/chart-releaser:latest'
    build_flag_templates:
      - '--label=org.label-schema.version={{ .Version }}'
      - '--label=org.label-schema.build-date={{ .Date }}'
      - '--label=org.label-schema.vcs-ref={{ .ShortCommit }}'
archives:
  -
    format: tar.gz
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    replacements:
      darwin: darwin
      linux: linux
