name: gosum

on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/gosum.yaml'
      - 'go.mod'
      - 'go.sum'

jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      -
        name: Tidy
        run: |
          rm -f go.sum
          go mod tidy
      -
        name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'deps: go mod tidy'
          title: 'deps: go mod tidy'
          body: |
            Current `go.mod` and `go.sum` don't match the source code.
          branch: go-mod-tidy
          branch-suffix: timestamp
          labels: automerge
